### ISSUE TITLE
Can not get information in backstage

### ISSUE THREAD

**Issue by bjsee** [TRIMM/plugin-dependencytrack#84]
Hello, I'm having trouble getting it to run and I think it's related to a misconfiguration. Could you possibly provide an example for the values of the URLs in the README? I believe that the `X-Api-Key` should contain the api-key and not the `DEPENDENCYTRACK_API_URL`.

My configuration looks like this:

```
integrations:
  dependencytrack:
    baseUrl: https://dependencytrack.mycompany.com

proxy:
  '/dependencytrack':
    target: 'https://dependencytrack.mycompany.com/api/v1'
    allowedMethods: [ 'GET' ]
    headers:
      X-Api-Key: 'l5ktqUe9uyNmmfsYinrRJ9xHLfhPumBZ'
```

If I make a GET request with this information using Postman, I receive a successful response.
However, in Backstage, I'm receiving the error message: "There is no Dependencytrack project with id 'dd89a9d0-49ff-42de-bffa-409ac1cadf0d'."

Here are the dependencytrack related log-entries:

```
[1] 2023-05-30T15:48:46.826Z proxy info [HPM] Proxy created: /dependencytrack  -> https://dependencytrack.mycompany.com/api/v1 type=plugin
[1] 2023-05-30T15:48:46.826Z proxy info [HPM] Proxy rewrite rule created: "^/api/proxy/dependencytrack/?" ~> "/" type=plugin
...
[1] 2023-05-30T15:48:54.021Z backstage info ::1 - - [30/May/2023:15:48:54 +0000] "GET /api/proxy/dependencytrack/api/v1/metrics/project/dd89a9d0-49ff-42de-bffa-409ac1cadf0d/current HTTP/1.1" 500 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" type=incomingRequest
...
[1] 2023-05-30T15:48:54.141Z backstage info ::1 - - [30/May/2023:15:48:54 +0000] "GET /api/proxy/dependencytrack/api/v1/finding/project/dd89a9d0-49ff-42de-bffa-409ac1cadf0d HTTP/1.1" 500 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" type=incomingRequest
```

I am not sure if the configuration is really correct. 
Could you possibly provide an example for the values of the URLs in the README

Thanks,
Björn
